version: "3"

volumes:
  basic-volume: {}

services:
  basic-db:
    image: postgres:9.6
    volumes:
      - basic-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=basic-db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
      - DJANGO_SETTINGS_MODULE=config.settings.development
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        pip install uwsgi
        python manage.py collectstatic --noinput
        python manage.py migrate --noinput
        uwsgi --http "0.0.0.0:8000" --module config.wsgi --master --processes 4 --threads 2
    restart: always
    volumes:
      - ./:/app/
