version: "3"

volumes:
  basic-volume: {}

services:
  basic-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=dev_secret_key
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - DJANGO_DB_HOST=basic-db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=basic_db
      - DJANGO_DB_USERNAME=basic_user
      - DJANGO_DB_PASSWORD=qwer1234
      - SUB_DB_HOST=sub-db
      - SUB_DB_PORT=5432
      - SUB_DB_NAME=sub_db
      - SUB_DB_USERNAME=sub_user
      - SUB_DB_PASSWORD=qwer1234
    expose:
      - '8000'
    restart: always
    volumes:
      - ./:/app/

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - basic-server
      
